---
- name: Restart MySQL
  ansible.builtin.service:
    name: mysql
    state: restarted

- name: Reload AppArmor
  ansible.builtin.command:
    cmd: apparmor_parser -r /etc/apparmor.d/usr.sbin.mysqld
  changed_when: true
