---
- name: Enabling kernel modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: "{{ kernel_modules | join('\n') }}\n"

- name: Load kernel modules
  ansible.builtin.modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ kernel_modules }}"
...