---
- name: Create cert-manager namespace
  ansible.builtin.command:
    cmd: kubectl create namespace cert-manager
  register: create_cm_ns
  failed_when: create_cm_ns.rc != 0 and 'already exists' not in create_cm_ns.stderr
  changed_when: create_cm_ns.rc == 0

- name: Create homelab CA secret
  ansible.builtin.command:
    cmd: >
      kubectl create secret tls homelab-ca-key-pair
      --namespace cert-manager
      --cert={{ role_path }}/files/pki/homelab-ca.crt
      --key={{ role_path }}/files/pki/homelab-ca.key
  register: create_ca_secret
  failed_when: create_ca_secret.rc != 0 and 'already exists' not in create_ca_secret.stderr
  changed_when: create_ca_secret.rc == 0
...
