---
- name: Install PostgreSQL
  ansible.builtin.apt:
    name:
      - "postgresql-{{ postgres_version }}"
      - python3-psycopg2
    state: present
    update_cache: true

- name: Allow external connections
  ansible.builtin.lineinfile:
    path: "/etc/postgresql/{{ postgres_version }}/main/postgresql.conf"
    regexp: "^#?listen_addresses"
    line: "listen_addresses = '*'"
  notify: Restart PostgreSQL

- name: Allow remote access in pg_hba.conf
  ansible.builtin.lineinfile:
    path: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
    line: "host  all  all  0.0.0.0/0  scram-sha-256"
  notify: Restart PostgreSQL

- name: Flush handlers before creating user and database
  ansible.builtin.meta: flush_handlers

- name: Create database user
  community.postgresql.postgresql_user:
    name: "{{ postgres_user }}"
    password: "{{ postgres_password }}"
    state: present
  become_user: postgres

- name: Create database
  community.postgresql.postgresql_db:
    name: "{{ postgres_db }}"
    owner: "{{ postgres_user }}"
    state: present
  become_user: postgres
...