---
- name: Create a .kube directory for the {{ k8s_admin_user }} user
  ansible.builtin.file:
    path: "/home/{{ k8s_admin_user }}/.kube"
    state: directory
    mode: '0755'
    owner: "{{ k8s_admin_user }}"
    group: "{{ k8s_admin_user }}"

- name: Copy admin.conf to the {{ k8s_admin_user }} user's kubeconfig
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ k8s_admin_user }}/.kube/config"
    remote_src: yes
    owner: "{{ k8s_admin_user }}"
    group: "{{ k8s_admin_user }}"
    mode: '0600'

- name: Create a .kube directory for the root user
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: '0755'

- name: Copy admin.conf to the root user's kubeconfig
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    mode: '0600'
...