apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/edsonoliveirarodz/homelab.git
    targetRevision: HEAD
    path: gitops/manifests/headlamp
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
