apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://codecentric.github.io/helm-charts
    chart: keycloakx
    targetRevision: "*"
    helm:
      values: |
        image:
          tag: "26.1.0"
        postgresql:
          enabled: false
        extraEnv: |
          - name: KC_DB
            value: postgres
          - name: KC_DB_URL
            value: jdbc:postgresql://keycloak-postgresql:5432/keycloak
          - name: KC_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: keycloak-credentials
                key: db-username
          - name: KC_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-credentials
                key: db-password
          - name: KC_HOSTNAME_STRICT
            value: "false"
          - name: KEYCLOAK_ADMIN
            value: admin
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-credentials
                key: admin-password
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
