apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-app
  namespace: echo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-app
  template:
    metadata:
      labels:
        app: echo-app
    spec:
      containers:
        - name: echo-app
          image: hashicorp/http-echo:1.0.0
          args:
            - "-text=Lab OK — ArgoCD + Gateway API + Cilium"
          ports:
            - containerPort: 5678
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              memory: 32Mi
